package main

import (
	"github.com/thegodeveloper/learning-go/internal/adapter"
	"github.com/thegodeveloper/learning-go/internal/arrays"
	"github.com/thegodeveloper/learning-go/internal/awspresignedurl"
	"github.com/thegodeveloper/learning-go/internal/basics"
	"github.com/thegodeveloper/learning-go/internal/books/learning_go/chapter5"
	"github.com/thegodeveloper/learning-go/internal/books/learning_go/chapter6"
	"github.com/thegodeveloper/learning-go/internal/boxui"
	"github.com/thegodeveloper/learning-go/internal/calculator"
	"github.com/thegodeveloper/learning-go/internal/channels"
	"github.com/thegodeveloper/learning-go/internal/closures"
	"github.com/thegodeveloper/learning-go/internal/concurrency"
	"github.com/thegodeveloper/learning-go/internal/constants"
	"github.com/thegodeveloper/learning-go/internal/deferpanic"
	"github.com/thegodeveloper/learning-go/internal/deferpanicrecover"
	"github.com/thegodeveloper/learning-go/internal/defersimplecat"
	"github.com/thegodeveloper/learning-go/internal/deferwithpanic"
	"github.com/thegodeveloper/learning-go/internal/enums"
	"github.com/thegodeveloper/learning-go/internal/forloops"
	"github.com/thegodeveloper/learning-go/internal/functionaloptions"
	"github.com/thegodeveloper/learning-go/internal/functions"
	"github.com/thegodeveloper/learning-go/internal/goroutines"
	"github.com/thegodeveloper/learning-go/internal/gotousecase"
	"github.com/thegodeveloper/learning-go/internal/helloworld"
	"github.com/thegodeveloper/learning-go/internal/input"
	"github.com/thegodeveloper/learning-go/internal/interfaces"
	"github.com/thegodeveloper/learning-go/internal/languagemechanics/escapeanalysis"
	"github.com/thegodeveloper/learning-go/internal/languagemechanics/memoryprofiling"
	"github.com/thegodeveloper/learning-go/internal/languagemechanics/stacksandpointers/frameboundaries"
	"github.com/thegodeveloper/learning-go/internal/languagemechanics/stacksandpointers/indirectmemoryaccess"
	"github.com/thegodeveloper/learning-go/internal/lengthcapacity"
	"github.com/thegodeveloper/learning-go/internal/logfatal"
	"github.com/thegodeveloper/learning-go/internal/loopsbranches"
	"github.com/thegodeveloper/learning-go/internal/maps"
	"github.com/thegodeveloper/learning-go/internal/openfile"
	"github.com/thegodeveloper/learning-go/internal/openpage"
	"github.com/thegodeveloper/learning-go/internal/packages"
	"github.com/thegodeveloper/learning-go/internal/passingarguments"
	"github.com/thegodeveloper/learning-go/internal/pointers"
	"github.com/thegodeveloper/learning-go/internal/printstars"
	"github.com/thegodeveloper/learning-go/internal/rand"
	"github.com/thegodeveloper/learning-go/internal/random_message"
	"github.com/thegodeveloper/learning-go/internal/runes"
	"github.com/thegodeveloper/learning-go/internal/sha256"
	"github.com/thegodeveloper/learning-go/internal/slices"
	"github.com/thegodeveloper/learning-go/internal/statistics"
	"github.com/thegodeveloper/learning-go/internal/strings"
	"github.com/thegodeveloper/learning-go/internal/structs"
	"github.com/thegodeveloper/learning-go/internal/sumtwonumbers"
	"github.com/thegodeveloper/learning-go/internal/switches"
	"github.com/thegodeveloper/learning-go/internal/syslog"
	"github.com/thegodeveloper/learning-go/internal/time"
	"github.com/thegodeveloper/learning-go/internal/typeconversions"
	"github.com/thegodeveloper/learning-go/internal/typediffarrayslicesitem"
	"github.com/thegodeveloper/learning-go/internal/unicode"
	"github.com/thegodeveloper/learning-go/internal/values"
	"github.com/thegodeveloper/learning-go/internal/variables"
	"github.com/thegodeveloper/learning-go/internal/wcalculator"
	"github.com/thegodeveloper/learning-go/internal/wcomplex"
	"github.com/thegodeveloper/learning-go/internal/wconstants"
	"github.com/thegodeveloper/learning-go/internal/wcountoccurrences"
	"github.com/thegodeveloper/learning-go/internal/wcustomtype"
	"github.com/thegodeveloper/learning-go/internal/wdefer"
	"github.com/thegodeveloper/learning-go/internal/webrouting"
	"github.com/thegodeveloper/learning-go/internal/werrorold"
	"github.com/thegodeveloper/learning-go/internal/werrors"
	"github.com/thegodeveloper/learning-go/internal/wexternalpackages"
	"github.com/thegodeveloper/learning-go/internal/wgoroutines"
	"github.com/thegodeveloper/learning-go/internal/which"
	"github.com/thegodeveloper/learning-go/internal/wintegertypes"
	"github.com/thegodeveloper/learning-go/internal/wjson"
	"github.com/thegodeveloper/learning-go/internal/wnilzero"
	"github.com/thegodeveloper/logging"
)

func main() {
	adapter.Index(false)
	arrays.Index(false)
	awspresignedurl.Index(false)
	basics.Index(false)
	boxui.Index(false)
	calculator.Index(false)
	chapter5.Index(false)
	chapter6.Index(false)
	channels.Index(false)
	closures.Index(false)
	concurrency.Index(false)
	constants.Index(false)
	deferpanic.Index(false)
	deferpanicrecover.Index(false)
	deferwithpanic.Index(false)
	defersimplecat.Index(false)
	enums.Index(false)
	escapeanalysis.Index(false)
	forloops.Index(false)
	frameboundaries.Index(false)
	functionaloptions.Index(false)
	functions.Index(false)
	goroutines.Index(false)
	gotousecase.Index(false)
	helloworld.Index(false)
	indirectmemoryaccess.Index(false)
	input.Index(false)
	interfaces.Index(false)
	lengthcapacity.Index(false)
	logfatal.Index(false)
	logging.Master(false, true, false)
	loopsbranches.Index(false)
	maps.Index(false)
	memoryprofiling.Index(false)
	openfile.Index(false)
	packages.Index(false)
	passingarguments.Index(false)
	pointers.Index(false)
	printstars.Index(false)
	randommessage.Index(false)
	runes.Index(false)
	sha256.Index(false)
	slices.Index(false)
	statistics.Index(false)
	strings.Index(false)
	structs.Index(false)
	sumtwonumbers.Index(false)
	switches.Index(false)
	syslog.Index(false)
	typediffarrayslicesitem.Index(false)
	unicode.Index(false)
	values.Index(false)
	variables.Index(false)
	wcalculator.Index(false)
	wcomplex.Index(false)
	wconstants.Index(false)
	wcountoccurrences.Index(false)
	wcustomtype.Index(false)
	wdefer.Index(false)
	werrorold.Index(false)
	wgoroutines.Index(false)
	wintegertypes.Index(false)
	wjson.Index(false)
	wnilzero.Index(false)
	openpage.Index(false)
	rand.Index(false)
	time.Index(false)
	typeconversions.Index(false)
	werrors.Index(false)
	wexternalpackages.Index(false)
	webrouting.Index(false)
	which.Index(false)

}
