package main

import (
	"github.com/thegodeveloper/learning-go/internal/adapter"
	"github.com/thegodeveloper/learning-go/internal/arrays"
	"github.com/thegodeveloper/learning-go/internal/basics"
	"github.com/thegodeveloper/learning-go/internal/books/learning_go/chapter5"
	"github.com/thegodeveloper/learning-go/internal/books/learning_go/chapter6"
	"github.com/thegodeveloper/learning-go/internal/box_ui"
	"github.com/thegodeveloper/learning-go/internal/calculator"
	"github.com/thegodeveloper/learning-go/internal/channels"
	"github.com/thegodeveloper/learning-go/internal/closures"
	"github.com/thegodeveloper/learning-go/internal/concurrency"
	"github.com/thegodeveloper/learning-go/internal/constants"
	"github.com/thegodeveloper/learning-go/internal/deferpanic"
	"github.com/thegodeveloper/learning-go/internal/deferpanicrecover"
	"github.com/thegodeveloper/learning-go/internal/defersimplecat"
	"github.com/thegodeveloper/learning-go/internal/deferwithpanic"
	"github.com/thegodeveloper/learning-go/internal/enums"
	"github.com/thegodeveloper/learning-go/internal/forloops"
	"github.com/thegodeveloper/learning-go/internal/functionaloptions"
	"github.com/thegodeveloper/learning-go/internal/functions"
	"github.com/thegodeveloper/learning-go/internal/goroutines"
	"github.com/thegodeveloper/learning-go/internal/gotousecase"
	"github.com/thegodeveloper/learning-go/internal/helloworld"
	"github.com/thegodeveloper/learning-go/internal/input"
	"github.com/thegodeveloper/learning-go/internal/interfaces"
	"github.com/thegodeveloper/learning-go/internal/languagemechanics/escapeanalysis"
	"github.com/thegodeveloper/learning-go/internal/languagemechanics/memoryprofiling"
	"github.com/thegodeveloper/learning-go/internal/languagemechanics/stacksandpointers/frameboundaries"
	"github.com/thegodeveloper/learning-go/internal/languagemechanics/stacksandpointers/indirectmemoryaccess"
	"github.com/thegodeveloper/learning-go/internal/lengthcapacity"
	"github.com/thegodeveloper/learning-go/internal/logfatal"
	"github.com/thegodeveloper/learning-go/internal/loopsbranches"
	"github.com/thegodeveloper/learning-go/internal/maps"
	"github.com/thegodeveloper/learning-go/internal/openfile"
	"github.com/thegodeveloper/learning-go/internal/packages"
	"github.com/thegodeveloper/learning-go/internal/passingarguments"
	"github.com/thegodeveloper/learning-go/internal/pointers"
	"github.com/thegodeveloper/learning-go/internal/printstars"
	"github.com/thegodeveloper/learning-go/internal/random_message"
	"github.com/thegodeveloper/learning-go/internal/runes"
	"github.com/thegodeveloper/learning-go/internal/sha256"
	"github.com/thegodeveloper/learning-go/internal/slices"
	"github.com/thegodeveloper/learning-go/internal/statistics"
	"github.com/thegodeveloper/learning-go/internal/strings"
	"github.com/thegodeveloper/learning-go/internal/structs"
	"github.com/thegodeveloper/learning-go/internal/sumtwonumbers"
	"github.com/thegodeveloper/learning-go/internal/switches"
	"github.com/thegodeveloper/learning-go/internal/syslog"
	"github.com/thegodeveloper/learning-go/internal/typediffarrayslicesitem"
	"github.com/thegodeveloper/learning-go/internal/unicode"
	"github.com/thegodeveloper/learning-go/internal/values"
	"github.com/thegodeveloper/learning-go/internal/variables"
	"github.com/thegodeveloper/learning-go/internal/wawspresignedurl"
	"github.com/thegodeveloper/learning-go/internal/wcalculator"
	"github.com/thegodeveloper/learning-go/internal/wcomplex"
	"github.com/thegodeveloper/learning-go/internal/wconstants"
	"github.com/thegodeveloper/learning-go/internal/wcountoccurrences"
	"github.com/thegodeveloper/learning-go/internal/wcustomtype"
	"github.com/thegodeveloper/learning-go/internal/wdefer"
	"github.com/thegodeveloper/learning-go/internal/webrouting"
	"github.com/thegodeveloper/learning-go/internal/werrorold"
	"github.com/thegodeveloper/learning-go/internal/werrors"
	"github.com/thegodeveloper/learning-go/internal/wexternalpackages"
	"github.com/thegodeveloper/learning-go/internal/wgoroutines"
	"github.com/thegodeveloper/learning-go/internal/which"
	"github.com/thegodeveloper/learning-go/internal/wintegertypes"
	"github.com/thegodeveloper/learning-go/internal/wjson"
	"github.com/thegodeveloper/learning-go/internal/wnilzero"
	"github.com/thegodeveloper/learning-go/internal/wopenpage"
	"github.com/thegodeveloper/learning-go/internal/wrand"
	"github.com/thegodeveloper/learning-go/internal/wtime"
	"github.com/thegodeveloper/learning-go/internal/wtypeconversions"
	"github.com/thegodeveloper/logging"
)

/*func init() {
	fmt.Println("init from my program")
}*/

func main() {
	adapter.Index(false)
	arrays.Index(false)
	basics.Index(false)
	box_ui.Master(false)
	calculator.Index(false)
	chapter5.Index(false)
	chapter6.Index(false)
	channels.Master(false)
	closures.Master(false)
	concurrency.Index(false)
	constants.Master(false)
	deferpanic.Master(false)
	deferpanicrecover.Master(false)
	deferwithpanic.Master(false)
	defersimplecat.Master(false)
	enums.Master(false)
	escapeanalysis.Master(false)
	forloops.Master(false)
	frameboundaries.Master(false)
	functionaloptions.Master(false)
	functions.Master(false)
	goroutines.Master(false)
	gotousecase.Master(false)
	helloworld.Master(false)
	indirectmemoryaccess.Master(false)
	input.Master(false)
	interfaces.Index(false)
	lengthcapacity.Master(false)
	logfatal.Master(false)
	logging.Master(false, true, false)
	loopsbranches.Master(false)
	maps.Master(false)
	memoryprofiling.Master(false)
	openfile.Master(false)
	packages.Index(false)
	passingarguments.Master(false)
	pointers.Master(false)
	printstars.Master(false)
	randommessage.Index(false)
	runes.Master(false)
	sha256.Master(false)
	slices.Master(false)
	statistics.Master(false)
	strings.Master(false)
	structs.Index(false)
	sumtwonumbers.Master(false)
	switches.Master(false)
	syslog.Master(false)
	typediffarrayslicesitem.Master(false)
	unicode.Master(false)
	values.Master(false)
	variables.Index(false)
	wawspresignedurl.Master(false)
	wcalculator.Master(false)
	wcomplex.Master(false)
	wconstants.Master(false)
	wcountoccurrences.Master(false)
	wcustomtype.Master(false)
	wdefer.Master(false)
	werrorold.Master(false)
	wgoroutines.Master(false)
	wintegertypes.Master(false)
	wjson.Master(false)
	wnilzero.Master(false)
	wopenpage.Master(false)
	wrand.Master(false)
	wtime.Master(false)
	wtypeconversions.Master(false)
	werrors.Master(false)
	wexternalpackages.Master(false)
	webrouting.Index(false)
	which.Master(false)

}
